# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

solve_qr_cpp <- function(A, v) {
    .Call('_hiperglm_solve_qr_cpp', PACKAGE = 'hiperglm', A, v)
}

